### ISSUE TITLE
can not run test 

### ISSUE THREAD

**Issue by binbinjiang1990** [fnemina/pyOSOAA#48]
>>> import pyOSOAA
>>> pyOSOAA.test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bjiang/Documents/pyOSOAA/pyOSOAA/osoaa.py", line 1386, in test
    s = OSOAA()
  File "/Users/bjiang/Documents/pyOSOAA/pyOSOAA/osoaa.py", line 1020, in __init__
    self.dirmie = DIRMIE(osoaaroot=self.root)
  File "/Users/bjiang/Documents/pyOSOAA/pyOSOAA/osoaa.py", line 198, in __init__
    self.hyd = os.path.join(osoaaroot, hid)
  File "/Users/bjiang/opt/anaconda3/envs/osoaa/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by binbinjiang1990** [comment]
Dear Fenqiao,

Thank you so much.

i think this my OSOAAROOT folder " export
OSOAA_ROOT="/Users/bjiang/Documents/pyOSOAA". "  I am not sure if it is
right or not.


Best

Binbin

**Comment by fengqiaogit** [comment]
`OSOAA_ROOT=/Users/bjiang/Documents/OSOAA` not `pyOSOAA`

**Comment by binbinjiang1990** [comment]
Dear Fengqiao,

Thank you for your reply. 

is that means  i should follow "OSOAA installation" step first in "pyOSOAA Documentation". But my system is mac, not ubuntu 18. is that works for me? 


Best

Binbin

**Comment by fnemina** [comment]
Dear Binbinjian

As Fengqiao described you need to first follow the OSOAA install procedure before moving to using pyOSOAA.

A few pointers for installing it on mac:

1. You can get the gfortran compiler from brew or from conda. If you use brew, a package manager similar to apt or dnf but for OSX, you can find the instruccions here: https://formulae.brew.sh/formula/gcc#default

2. You need to set your export, the OSOAA_ROOT variable, in the config file of your shell. It should be .bashrc or .zshrc

After doing this two things the test should work, but feel free to ask me anytime.

Best
Fran

**Comment by binbinjiang1990** [comment]
Dear Fran,

Thanks a lot. I already tried "brew" instead of "apt" . also install  "gfortran
ksh93 git make" with brew one by one. But I tried to " make -f
$OSOAA_ROOT/gen/Makefile_OSOAA.gfortran", but it failed. The details are
below.

By the way "export OSOAA_ROOT="/Users/bjiang/Documents/OSOAA" it was
already been changed .


Best

Binbin


(base) ***@***.*** gen % make -f
/Users/bjiang/Documents/OSOAA/gen/Makefile_OSOAA.gfortran

make: *** No rule to make target `/src/OSOAA_MAIN.F', needed by
`/obj/OSOAA_MAIN.o'.  Stop.

**Comment by fnemina** [comment]
Hello,  two questions:
1. Did you add the OSOAA_ROOT variable to .bashrc or the .zshrc? 
2. Can you please give me the output of the `echo $OSOAA_ROOT` command.

**Comment by binbinjiang1990** [comment]
Yes, I did.

my echo command is below, in figure.

Best, Binbin

(base) ***@***.*** ~ % echo 'export
OSOAA_ROOT="/Users/bjiang/Documents/OSOAA"' >> ~/.bashrc
[image: Screen Shot 2023-04-06 at 10.36.48.png]

**Comment by fnemina** [comment]
Hello BinBin,

it seems that the image didn't to get to me. This is how the output should look like

<img width="399" alt="Screenshot 2023-04-19 at 09 22 41" src="https://user-images.githubusercontent.com/2727433/233073619-eefccd7c-ab99-4d0b-9758-83b06bf00ab4.png">

For what you have been telling me, I guess what is happening is you are using a different shell to the one where configured the OSOAA_ROOT variable. You can check your current shell using the command `ps $$`

<img width="359" alt="Screenshot 2023-04-19 at 09 24 14" src="https://user-images.githubusercontent.com/2727433/233073870-2be97111-882d-4862-9b95-b95c8114cbb0.png">

Best

**Comment by binbinjiang1990** [comment]
Dear Fnemina/Pyosoaa,

Sorry for the late reply.  Here is my result, below. thanks



Best

Binbin


[image: Screen Shot 2023-06-06 at 14.34.31.png]
